spring.application.name=integration

spring.security.oauth2.client.registration.hubspot.client-id=0973c249-87f2-4a12-93bf-dcac2a2c0313
spring.security.oauth2.client.registration.hubspot.client-secret=d6d137fa-e8f7-4af1-a918-8ba4b07a390a
spring.security.oauth2.client.registration.hubspot.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.hubspot.redirect-uri=http://localhost:8080/login/oauth2/code/hubspot
spring.security.oauth2.client.registration.hubspot.scope=oauth


spring.security.oauth2.client.provider.hubspot.authorization-uri=https://app.hubspot.com/oauth/authorize
spring.security.oauth2.client.provider.hubspot.token-uri=https://api.hubapi.com/oauth/v1/token

server.servlet.session.timeout=1m

logging.level.org.springframework.security=TRACE